{'author': 'Nedas Zilinskas',
 'category': 'Website',
 'currency': 'EUR',
 'data': ['data/website_cookiebar.xml',
          'security/ir.model.access.csv',
          'views/assets.xml',
          'views/website_cookiebar.xml',
          'views/templates.xml'],
 'demo': [],
 'depends': ['website'],
 'external_dependencies': [],
 'images': ['static/description/main_screenshot.png'],
 'installable': True,
 'license': 'AGPL-3',
 'live_test_url': 'https://demo.minilini.com/page/start/website_cookiebar/12.0',
 'name': 'EU Cookie Law Notice',
 'price': 15.0,
 'qweb': [],
 'summary': 'Informs visitors about storing cookies on their browser',
 'support': 'nedas.zilinskas@gmail.com',
 'version': '12.0.1.0.0',
 'website': 'https://demo.minilini.com'}

